### ISSUE TITLE
Saving using the refactored manager

### ISSUE THREAD

**Issue by NITHISHM2410** [google/orbax#941]
`options = ocp.CheckpointManagerOptions(max_to_keep=2, create=True)`
`with ocp.CheckpointManager(directory='/tmp/ckpt2/') as mngr:`
      `     print()`

shows error
`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`Cell In[20], line 2`
 `     1 options = ocp.CheckpointManagerOptions(max_to_keep=2, create=True)`
`----> 2 with ocp.CheckpointManager(directory='/tmp/ckpt2/') as mngr:`
`      3     print()`

`AttributeError: __enter__`

I tried saving different pytrees and tried without saving any pytree , like the snippet above.

orbax-checkpoint version: 0.5.0
System: kaggle notebook with GPU T4 x2

Can I get a solution please?

**Comment by cpgaffney1** [comment]
0.5.0 is pretty old, the documentation is based off the latest version. The context manager should have been introduced by 0.5.8.

**Comment by NITHISHM2410** [comment]
I tried using the latest version of orbax-checkpoint using refactored checkpoint manager. Used this code:

`options = ocp.CheckpointManagerOptions()`
`with ocp.CheckpointManager(
`  ocp.test_utils.erase_and_create_em`pty('/tmp/ckpt2/'),`
`  options=options,`
`) as mngr:`

`  mngr.save(0, args=ocp.args.StandardSave(pytree))`
`  mngr.wait_until_finished()`


got this error:

`AttributeError: module 'jax' has no attribute 'tree' 1.

Versions:
jax   -   0.4.23 
flax    -   0.8.2
orbax.checkpoint    -   0.5.16

**Comment by cpgaffney1** [comment]
We just added this in the last few days, but going forward there will be a designated minimum supported JAX version. Right now that version is 'jax >= 0.4.25'.

**Comment by NITHISHM2410** [comment]
@cpgaffney1 after updating jax to 0.4.26 , checkpointing works. thq
