### ISSUE TITLE
AttributeError: module 'orbax.checkpoint.metadata' has no attribute 'Metadata'

### ISSUE THREAD

**Issue by hanzhi713** [google/orbax#1294]
After upgrading orbax to 0.8.0, I encountered this error.

Also documentation also broke: https://orbax.readthedocs.io/en/latest/guides/checkpoint/custom_handlers.html

**Comment by hanzhi713** [comment]
Looks like this `Metadata` class needs to be imported like
```
from orbax.checkpoint._src.metadata.value import Metadata
```

Shouldn't this be in the user-facing API?

**Comment by cpgaffney1** [comment]
Thanks for spotting, our tests that are supposed to catch docs breakages appear not to be working. Will fix ASAP.

**Comment by hanzhi713** [comment]
Should be fixed in the latest orbax.
